# accessible as site.*
title: "Ian Moriarty"
description: "Ian Moriarty"
url: "http://iann.github.com"
files: "http://iann.github.com/files/" 
author: "Ian Moriarty"
email: "rominet@gmail.com"

# --server --auto
server: true
auto: true

# default './_site'
destination: './_site'

# turn on pygment syntax highlighting
pygments: true

# pagination
# paginate: 8

## permalink style: http://wiki.github.com/mojombo/jekyll/permalinks
permalink: pretty

# use rdiscount for markdown
markdown: rdiscount

# maruku settings
maruku:
  png_dir: files/latex
  png_url: /images/latex
